- name: Check transparent_hugepage exists
  stat:
    path: /sys/kernel/mm/transparent_hugepage
  register: transparent_hugepage_exits

- name: Configure transparent_hugepage/enabled never 
  command: echo 'never' > /sys/kernel/mm/transparent_hugepage/enabled
  when: transparent_hugepage_exits.stat.exists

- name: Configure transparent_hugepage/defrag never 
  command: echo 'never' > /sys/kernel/mm/transparent_hugepage/defrag
  when: transparent_hugepage_exits.stat.exists

- name: Create hostfiles
  template:
    src: hosts.j2
    dest: /etc/hosts

# https://ask.ubuntu.com/questions/842592/apt-get-fails-on-16-04-or-18-04-installing-mongodb
- name: Add an apt key by id from a keyserver
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 4B7C549A058F8B6B

- name: Create the /etc/apt/sources.list.d/mongodb-org-4.2.list file for Ubuntu 18.04 (Bionic) nonroot
  shell: echo "deb [arch=amd64] http://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list
  when: remote_user != "root"
  
- name: Create the /etc/apt/sources.list.d/mongodb-org-4.2.list file for Ubuntu 18.04 (Bionic) root
  shell: echo "deb [arch=amd64] http://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-4.2.list
  when: remote_user == "root"

- name: apt-get update
  apt:
    update_cache: yes

- name: Install Mongodb
  apt:
    name: mongodb-org