all:
    hosts:
    children:
        mongodb:
            hosts:
                mongo-1.your-domain.fr:
                    host_name: mongo-1
                    host_ip: "213.32.78.22"
                    host_private_ip: "55.8.4.3"
                    cron_renew_day: "1"
                mongo-2.your-domain.fr:
                    host_name: mongo-2
                    host_ip: "149.202.179.71"
                    host_private_ip: "55.8.4.2"
                    cron_renew_day: "2"
                mongo-3.your-domain.fr:
                    host_name: mongo-3
                    host_ip: "149.202.181.179"
                    host_private_ip: "55.8.4.1"
                    cron_renew_day: "3"
                mongo-arbiter.your-domain.fr:
                    host_name: mongo-arbiter
                    host_ip: "149.202.179.53"
                    host_private_ip: "55.8.4.0"
                    cron_renew_day: "4"
        primary:
            hosts:
                mongo-1.your-domain.fr:
        secondaries:
            hosts:
                mongo-2.your-domain.fr:
                    priority: 1
                mongo-3.your-domain.fr:
                    priority: 1
        arbiter:
            hosts:
                mongo-arbiter.your-domain.fr:
        monitoring_server:
            hosts:
                mongo-arbiter.your-domain.fr:
        monitoring_clients:
            hosts:
                mongo-1.your-domain.fr:
                mongo-2.your-domain.fr:
                mongo-3.your-domain.fr:
        backup_server:
            hosts:
                mongo-arbiter.your-domain.fr:
    vars:
        remote_user: ubuntu
        mongodb_replicaset_name: rs0
        mongodb_db_path: "/mnt/mongo_data"
        mongodb_user_user_admin_any_database_name: siteUserAdmin
        mongodb_user_user_admin_any_database_password: "strong-pwd-1"
        mongodb_user_root_name: siteRootAdmin
        mongodb_user_root_password: "strong-pwd-2"
        mongodb_main_database: siteMainDataBase
        mongodb_user_readwrite_main_database_name: "siteDataBaseUser"
        mongodb_user_readwrite_main_database_password: "strong-pwd-3"
        partitioning_device_name: "/dev/nvme0n1"
        partitioning_partition_name: "/dev/nvme0n1p1"
        partitioning_luks_passphrase: "strong-pwd-4"
        partitioning_luks_name: cryptolvm
        partitioning_vg_name: mongo_vg
        partitioning_lv_name: mongo_data
        certbot_admin_email: your@email.com
        monitoring_password: "strong-pwd-5"
        monitoring_db_user_name: "pmm"
        monitoring_db_user_password: "strong-pwd-5"
        backup_db_user_name: backup
        backup_db_user_password: "strong-pwd-6"
        backup_region: "eu-west-3"
        backup_bucket: "my-project-mongodb-backup"
        backup_secret: "aws-secret"
        backup_public: "aws-public"
        backup_minute: "30"
        backup_hour: "1"
        